# Generated by Django 4.2.16 on 2024-10-17 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cases'),
    ]

    operations = [
        migrations.AddField(
            model_name='cases',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='api.actives_and_project'),
        ),
        migrations.AlterField(
            model_name='cases',
            name='theme',
            field=models.CharField(max_length=250),
        ),
    ]
