# Generated by Django 4.2.16 on 2024-10-17 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_cases_activity_alter_cases_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cases',
            name='activity',
        ),
    ]
