# Generated by Django 4.2.16 on 2024-10-17 17:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_cases_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cases',
            name='activity',
        ),
        migrations.AddField(
            model_name='actives_and_project',
            name='active',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actives_and_project', to='api.cases'),
        ),
        migrations.AddField(
            model_name='actives_and_project',
            name='comment',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='actives_and_project',
            name='first_question',
            field=models.CharField(choices=[('1', 'Да'), ('2', 'Нет')], default=None, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='actives_and_project',
            name='fourth_comment_question',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='actives_and_project',
            name='fourth_question',
            field=models.CharField(choices=[('1', 'Да'), ('2', 'Нет')], default=None, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='actives_and_project',
            name='rating',
            field=models.IntegerField(default=None, null=True, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(-1)]),
        ),
        migrations.AddField(
            model_name='actives_and_project',
            name='second_question',
            field=models.CharField(choices=[('1', 'Да'), ('2', 'Нет')], default=None, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='actives_and_project',
            name='third_question',
            field=models.CharField(choices=[('1', 'Да'), ('2', 'Нет')], default=None, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='cases',
            name='users',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cases', to=settings.AUTH_USER_MODEL),
        ),
    ]
