# Generated by Django 4.2.16 on 2024-10-17 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_cases_activity_actives_and_project_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actives_and_project',
            name='code',
            field=models.CharField(max_length=20),
        ),
    ]
