# Generated by Django 2.2.19 on 2024-03-17 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_auto_20240311_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='active_value',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='active',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='manager', to='activity.Activity'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='manager_name',
            field=models.TextField(unique=True),
        ),
    ]
