# Generated by Django 2.2.19 on 2024-03-17 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_auto_20240317_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='active_value',
            field=models.CharField(max_length=20),
        ),
    ]
