# Generated by Django 2.2.19 on 2024-03-20 11:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0006_auto_20240317_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='first_question',
            field=models.CharField(choices=[('1', 'Yes'), ('0', 'No')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='manager',
            name='second_question',
            field=models.CharField(choices=[('1', 'Yes'), ('0', 'No')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='manager',
            name='third_question',
            field=models.CharField(choices=[('1', 'Yes'), ('0', 'No')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='manager',
            name='rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(-1)]),
        ),
    ]
