# Generated by Django 2.2.19 on 2024-03-20 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0007_auto_20240320_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='first_question',
            field=models.CharField(choices=[(1, 'Да'), (0, 'Нет')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='manager',
            name='second_question',
            field=models.CharField(choices=[(1, 'Да'), (0, 'Нет')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='manager',
            name='third_question',
            field=models.CharField(choices=[(1, 'Да'), (0, 'Нет')], default='1', max_length=1),
        ),
    ]
