# Generated by Django 2.2.19 on 2024-03-21 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0008_auto_20240320_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='project_file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
