# Generated by Django 2.2.19 on 2024-03-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0009_activity_project_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='first_question',
            field=models.CharField(choices=[('1', 'Да'), ('0', 'Нет')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='manager',
            name='second_question',
            field=models.CharField(choices=[('1', 'Да'), ('0', 'Нет')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='manager',
            name='third_question',
            field=models.CharField(choices=[('1', 'Да'), ('0', 'Нет')], default='1', max_length=1),
        ),
    ]
