# Generated by Django 2.2.19 on 2024-04-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0011_auto_20240410_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='first_question',
            field=models.CharField(choices=[('2', '-'), ('1', 'Да'), ('0', 'Нет')], default='2', max_length=1),
        ),
        migrations.AlterField(
            model_name='manager',
            name='fourth_question',
            field=models.CharField(choices=[('2', '-'), ('1', 'Да'), ('0', 'Нет')], default='2', max_length=1),
        ),
        migrations.AlterField(
            model_name='manager',
            name='second_question',
            field=models.CharField(choices=[('2', '-'), ('1', 'Да'), ('0', 'Нет')], default='2', max_length=1),
        ),
        migrations.AlterField(
            model_name='manager',
            name='third_question',
            field=models.CharField(choices=[('2', '-'), ('1', 'Да'), ('0', 'Нет')], default='2', max_length=1),
        ),
    ]
