# Generated by Django 2.2.19 on 2024-07-15 11:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity', '0012_auto_20240418_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='fourth_comment_question',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='active',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manager', to='activity.Activity'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='comment',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='first_question',
            field=models.CharField(choices=[('1', 'Да'), ('2', 'Нет')], default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='fourth_question',
            field=models.CharField(choices=[('1', 'Да'), ('2', 'Нет')], default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='rating',
            field=models.IntegerField(default=None, null=True, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(-1)]),
        ),
        migrations.AlterField(
            model_name='manager',
            name='second_question',
            field=models.CharField(choices=[('1', 'Да'), ('2', 'Нет')], default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='third_question',
            field=models.CharField(choices=[('1', 'Да'), ('2', 'Нет')], default=None, max_length=1, null=True),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(null=True)),
                ('feedback_comment', models.TextField(blank=True, max_length=250, null=True)),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feedback', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
