# Generated by Django 2.2.19 on 2024-10-16 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0013_auto_20240715_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='project_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='activity',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='manager',
            name='active',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='managers', to='activity.Activity'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='manager_name',
            field=models.CharField(max_length=50),
        ),
    ]
