# Generated by Django 2.2.19 on 2024-10-16 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0014_auto_20241016_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='project_file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='manager',
            name='rating',
            field=models.IntegerField(default=None),
        ),
    ]
