# Generated by Django 2.2.19 on 2024-10-16 18:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0016_auto_20241016_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='project_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='rating',
            field=models.IntegerField(default=None, null=True, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(-1)]),
        ),
    ]
