# Generated by Django 4.2.16 on 2024-10-20 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0017_auto_20241016_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='active',
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='Manager',
        ),
    ]
